SELECT
	ID_PRODUTO,
	NOME,
	PRECO,
	CONCAT(CAST(DESCONTO * 100 AS INT),'%') AS PERCENTUAL_DESCONTO,
	DIA_DESCONTO,
	CASE
		WHEN DAY(GETDATE()) = DIA_DESCONTO THEN DESCONTO * PRECO
		ELSE 0
		END PRECO_DESCONTO,
	IIF(DAY(GETDATE()) = DIA_DESCONTO, PRECO - (DESCONTO * PRECO), PRECO) AS PRECO_PRODUTO_COM_DESCONTO
FROM
	(VALUES 
		(1, 'NOTEBOOK', 3500, 0.3, 15), 
		(2, 'TECLADO', 300, 0.2, 5), 
		(3, 'MOUSE', 125, 0.1, 20),
		(4, 'MONITOR', 900, 0.4, 30),
		(5, 'PLACA DE VÍDEO', 280, 0.3, 10)
	) AS TB
	(
		ID_PRODUTO,
		NOME,
		PRECO,
		DESCONTO,
		DIA_DESCONTO
	);