DECLARE @DATA DATETIME = GETDATE();

SELECT
	@DATA AS DATA_ATUAL,
	DATEADD(HOUR, 1, @DATA) AS MAIS_1_HORA,			-- Adiciona 1 hora
	DATEADD(MINUTE, 10, @DATA) AS MAIS_10_MINUTOS,	-- Adiciona 10 minutos
	DATEADD(SECOND, 30, @DATA) AS MAIS_30_SEGUNDOS;	-- Adiciona 30 segundos