DECLARE @DATA DATETIME = GETDATE();

SELECT
	@DATA AS DATA_ATUAL,
	DATEADD(DAY, 15, @DATA) AS MAIS_15_DIAS,		-- Adiciona 15 dias
	DATEADD(MONTH, 6, @DATA) AS MAIS_6_MESES,		-- Adiciona 6 meses
	DATEADD(YEAR, 1, @DATA) AS MAIS_1_ANO;