CREATE FUNCTION FNT_API_VIACEP
(
	@CEP VARCHAR(8)
)
RETURNS @TBL TABLE
(
	STATUS_HTTP VARCHAR(10),
	RESPONSE_TEXT VARCHAR(MAX)
)
AS
BEGIN

	DECLARE @OBJECT_TOKEN INT;
	DECLARE @RESPONSE_TEXT VARCHAR(8000);
	DECLARE @STATUS INT;
	DECLARE @URL_API VARCHAR(MAX) = 'https://viacep.com.br/ws/'+@CEP+'/json/';

	EXEC sp_OACreate 'MSXML2.ServerXMLHTTP', @OBJECT_TOKEN OUT;
	EXEC sp_OAMethod @OBJECT_TOKEN, 'open', NULL, 'GET', @URL_API, false; 
	EXEC sp_OAMethod @OBJECT_TOKEN, 'send';
	EXEC sp_OAGetProperty @OBJECT_TOKEN, 'status', @STATUS OUTPUT;
	EXEC sp_OAMethod @OBJECT_TOKEN, 'responseText', @RESPONSE_TEXT OUTPUT;
	EXEC sp_OADestroy @OBJECT_TOKEN;

	INSERT INTO @TBL SELECT @STATUS, @RESPONSE_TEXT;

	RETURN;

END;